-- Core identity and hardware tables (Phase 2).
--
-- Statuses are TEXT + CHECK rather than Postgres ENUM types: adding a value
-- later is a simple constraint change, and the mapping to Rust enums lives in
-- one place (the domain's `as_str` / `FromStr`). All timestamps are UTC
-- (TIMESTAMPTZ); IDs are UUIDv7 generated by the application.

CREATE TABLE users (
    id          UUID        PRIMARY KEY,
    name        TEXT        NOT NULL CHECK (char_length(name) BETWEEN 1 AND 100),
    email       TEXT        NOT NULL CHECK (email = lower(email)),
    status      TEXT        NOT NULL CHECK (status IN ('active', 'suspended', 'archived')),
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE access_cards (
    id           UUID        PRIMARY KEY,
    -- RESTRICT: users are archived, never deleted, so card history stays intact.
    user_id      UUID        NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    card_number  TEXT        NOT NULL CHECK (card_number = upper(card_number)),
    status       TEXT        NOT NULL CHECK (status IN ('active', 'suspended', 'revoked', 'expired')),
    issued_at    TIMESTAMPTZ NOT NULL,
    expires_at   TIMESTAMPTZ,
    CONSTRAINT access_cards_card_number_key UNIQUE (card_number),
    CONSTRAINT access_cards_expiry_after_issue CHECK (expires_at IS NULL OR expires_at > issued_at)
);

-- Postgres does not index foreign keys automatically.
CREATE INDEX access_cards_user_id_idx ON access_cards (user_id);

CREATE TABLE doors (
    id             UUID        PRIMARY KEY,
    name           TEXT        NOT NULL CHECK (char_length(name) BETWEEN 1 AND 100),
    location       TEXT        NOT NULL CHECK (char_length(location) BETWEEN 1 AND 200),
    controller_id  TEXT        NOT NULL,
    status         TEXT        NOT NULL CHECK (status IN ('online', 'offline', 'disabled')),
    created_at     TIMESTAMPTZ NOT NULL
);

-- Controllers look up their doors when they report status.
CREATE INDEX doors_controller_id_idx ON doors (controller_id);
